git:
    submodules: true
language: node_js
node_js:
  - "6.10.2"
dist: trusty
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y gcc-multilib nasm gdb
script:
  - chmod +x "./.travis-run-$TEST_SUITE.sh"
  - "./.travis-run-$TEST_SUITE.sh"
env:
#    - TEST_SUITE=unit
#    - TEST_SUITE=integration
#    - TEST_SUITE=integration-acpi
#    - TEST_SUITE=unit-qemu
#    - TEST_SUITE=nasm
    - TEST_SUITE=free
matrix:
  allow_failures:
#    - env: TEST_SUITE=unit-qemu
    - env: TEST_SUITE=free
